// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nqkvzjwylvmxvmttgtpk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5xa3Z6and5bHZteHZtdHRndHBrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNzQ0NjcsImV4cCI6MjA2Mzk1MDQ2N30.WMDLTAXDfp83kW-RD3Xi00dkVfkGYK25N8faqWq48yg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);